# Generated by Django 4.2.16 on 2024-11-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('author', models.TextField(max_length=255)),
                ('genre', models.TextField(max_length=100)),
                ('current', models.IntegerField(default=0)),
                ('readed', models.IntegerField(default=0)),
                ('readedOn', models.TextField(blank=True, max_length=100, null=True)),
                ('rating', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
