# Generated by Django 4.2.16 on 2024-11-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='en',
            field=models.IntegerField(default=0),
        ),
    ]
