# Generated by Django 4.2.16 on 2024-11-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_books_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='challengeid',
            field=models.IntegerField(default=0),
        ),
    ]
