# Generated by Django 4.2.16 on 2024-11-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_books_author_alter_books_challengeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
