# Generated by Django 4.2.16 on 2024-11-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_books_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('nrofbooks', models.IntegerField(default=0)),
            ],
        ),
    ]
